use_frameworks!


source 'https://github.com/A-Jun/XiaoYuSpecs.git'
source 'https://github.com/CocoaPods/Specs.git'

target 'BengChuang_Sport_Example' do
  pod 'BengChuang_Sport', :path => '../'

  target 'BengChuang_Sport_Tests' do
    inherit! :search_paths

    
  end
end
